TIMESTAMP = "timestamp"
TIME_DELTA = "time_delta"
WEATHER_TEMP = "weather_temp"
HOME_NAME = "home_name"
TEMP_AT_BOILER_OUT = "BOILER"
TEMP_AT_HOME_IN = "temp_at_home_in"
TEMP_AT_HOME_OUT = "temp_at_home_out"

SOFT_M_TEMP_GRAPH_WEATHER_TEMP = "t"
SOFT_M_TEMP_GRAPH_TEMP_AT_HOME_IN = "in_t"
SOFT_M_TEMP_GRAPH_TEMP_AT_HOME_OUT = "out_t"

SOFT_M_WEATHER_TEMP = "temp"
SOFT_M_WEATHER_TIME = "time"
SOFT_M_WEATHER_DATE = "date"
