TIMESTAMP = "timestamp"
TIME_DELTA = "time_delta"
WEATHER_TEMP = "weather_temp"
HOME_NAME = "home_name"
BOILER_OUT_TEMP = "BOILER"
FORWARD_PIPE_TEMP = "forward_pipe_temp"
BACKWARD_PIPE_TEMP = "backward_pipe_temp"

SOFT_M_TIMESTAMP = "dTimeStamp"

SOFT_M_TEMP_GRAPH_WEATHER_TEMP = "t"
SOFT_M_TEMP_GRAPH_TEMP_AT_HOME_IN = "in_t"
SOFT_M_TEMP_GRAPH_TEMP_AT_HOME_OUT = "out_t"

SOFT_M_WEATHER_TEMP = "temp"
SOFT_M_WEATHER_TIME = "time"
SOFT_M_WEATHER_DATE = "date"

SOFT_M_PIPE_NUMBER = "nTC"

SOFT_M_FORWARD_PIPE_TEMP = "t1"
SOFT_M_BACKWARD_PIPE_TEMP = "t2"
